name: Feature Template
description: 기능 추가할 때 쓰는 템플릿
title: "[feature]: Feature Title"
labels: ["✨Feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 타이머 화면 그리기
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 스크린샷
      placeholder: 이미지를 드롭다운해주세요.
    validations:
      required: false
  - type: input
    id: expected-period
    attributes:
      label: 예상 작업 기간
      placeholder: ~ MM/DD(E) ex. ~ 07/12(화)
    validations:
      required: true
  - type: input
    id: real-period
    attributes:
      label: 실제 작업 기간(PR 작성 직전에 수정
      placeholder: ~ MM/DD(E) ex. ~ 07/12(화)
    validations:
      required: false
